card/urls.py
from django.conf.urls import url
# 添加路由
from . import views
urlpatterns = [
    url(r'^$', views.login),
    url(r'^login/$', views.login),
    url(r'^register/$', views.register),
    url('index/', views.index),
    url('cardtest', views.cardtest),
    url('logout/', views.logout),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url('admin/', admin.site.urls),

    url(r'', include('card.urls')),
]

card/models.py
from MySQLdb.constants.FLAG import UNIQUE
from django.db import models
class User(models.Model):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )

    username = models.CharField(max_length=128, unique=True, verbose_name='用户名')
    password = models.CharField(max_length=256, verbose_name='密码')
    email = models.EmailField(unique=True, verbose_name='邮箱')
    sex = models.CharField(max_length=32, choices=gender, default="男", verbose_name='性别')
    c_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    card = models.CharField(max_length=20, default="", verbose_name='卡号')
    name = models.CharField(max_length=20, default="", verbose_name='姓名')
    onlyid = models.CharField(max_length=50, default="", verbose_name='身份证号')
    def __str__(self):
        return self.name
    class Meta:
        ordering = ["-c_time"]
        verbose_name = "用户"
        verbose_name_plural = "用户"
        db_table = "userlogin"
class Cardmoney(models.Model):
    card = models.CharField(max_length=32, default='', verbose_name='卡号')
    rest_money = models.CharField(max_length=32, verbose_name='剩余金额')
    consume_money = models.CharField(max_length=32, verbose_name='消费金额')
    consume_time = models.DateTimeField(auto_now_add=True, verbose_name='消费时间')
    username = models.CharField(max_length=32, default='', verbose_name='用户名')
    cardnum = models.ForeignKey(User, on_delete=models.CASCADE, default='', verbose_name='外键')
    class Meta:
        ordering = ["-consume_time"]
        verbose_name = "消费表"
        verbose_name_plural = "消费表"
        db_table = "userconsume"

card/forms.py
from django import forms


class UserForm(forms.Form):
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "用户名",'autofocus': ''}))
    password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder': "密码"}))


class RegisterForm(forms.Form):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'用户名'}), )
    password1 = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder': "密码",'autofocus': ''}))
    password2 = forms.CharField(label="确认密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': "确认密码",'autofocus': ''}))
    email = forms.EmailField(label="邮箱地址", widget=forms.EmailInput(attrs={'class': 'form-control','placeholder': "邮箱地址",'autofocus': ''}))
    card = forms.CharField(label="校园卡号", max_length=20, widget=forms.TextInput(attrs={'class': 'form-control','placeholder': "校园卡号",'autofocus': ''}))
    sex = forms.ChoiceField(label='性别', choices=gender)
    name = forms.CharField(label="姓名", max_length=20,widget=forms.TextInput(attrs={'class': 'form-control','placeholder': "真实姓名",'autofocus': ''}))
    onlyid = forms.CharField(label="身份证号码", max_length=20,widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "身份证号",'autofocus': ''}))

class CardForm(forms.Form):
    rest_money = forms.CharField(max_length=128, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'剩余金额'}), )
    consume_money = forms.CharField(max_length=128, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'消费金额'}), )

templates/cardApp/cardtest.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" href="//apps.bdimg.com/libs/bootstrap/3.3.4/css/bootstrap.min.css">
<script src="https://cdn.staticfile.org/angular.js/1.4.6/angular.min.js"></script>
</head>
<body>
<div class="container">
<h3>用户信息</h3>
<table class="table table-striped">
  <thead>
 <tr>
    <th>#</th>
     <th>校园卡卡号</th>
     <th>用户名</th>
     <th>消费时间</th>
     <th>消费金额</th>
     <th>剩余金额</th>
  </tr>
  </thead>
  <tbody>
     {% for foo in data_list %}
       <tr>
           <td>{{ foo.pk }}</td>
           <td>{{ foo.card }}</td>
           <td>{{ foo.username }}</td>
           <td>{{ foo.consume_time}}</td>
           <td>{{ foo.consume_money}}</td>
           <td>{{ foo.rest_money}}</td>
       </tr>
    {%endfor%}
  </tbody>
</table>
 <div class="pagination" style="margin-top: -50px;width: 550px; margin-left: 280px;">
        <ul class="pagination">
                <ul class="pagination pagination-sm">
                        {{ page_obj.page_str|safe }}
                </ul>
        </ul>
 </div>
<h3 ng-show="edit">读卡器模拟</h3>
<h3 ng-hide="edit">消费模拟</h3>
<form class="form-horizontal" method="post" action="/cardtest/">
 {% csrf_token %}
  <div class="form-group">
    <label class="col-sm-2 control-label">卡号:</label>
    <div class="col-sm-10">
        {% for foo in listinfo %}
            {{ foo.card }}
        {% endfor %}
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">姓名:</label>
    <div class="col-sm-10">
        {% for foo in listinfo %}
            {{ foo.name }}
        {% endfor %}
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">消费金额:</label>
    <div class="col-sm-10">
        {{ card_form.consume_money }}
{#        <input type="text" name="consume" class="form-control"  value=""/>#}
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">剩余金额:</label>
    <div class="col-sm-10">
        {{ card_form.rest_money }}
{#        <input type="text" name="rest" class="form-control"  value=""/>#}
    </div>
  </div>
    <div class="form-input">
        <input type="submit" name='' value='提交'>
    </div>
</form>
</div>
</body>
</html>

templates/cardApp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles%}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>校园卡支付管理系统</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body data-vide-bg="{% static 'img/oceans.mp4' %}">
<form class="form-login" action="/login/" method="post">
      {% if message %}
       <div class="alert alert-warning">{{ message }}</div>
       {% endif %}
       {% csrf_token %}

  <div class="login-form">
    <h2>欢迎登陆</h2>
    <div class="form-input">
        {{ login_form.username.label_tag }}
        {{ login_form.username }}
{#      <input type="text" id="id_username" class="form-control" name="username" autofocus required placeholder="用户名">#}
    </div>
    <div class="form-input">
        {{ login_form.password.label_tag }}
        {{ login_form.password }}
{#      <input type="password" class="form-control" id="id_password" placeholder="密码" name="password" required>#}
    </div>
    <div class="form-input">
      <input type="submit" name='' value='登陆'>
    </div>
    <a href="/register/" class="forget">新用户注册</a>
  </div>
</form>
    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'js/jquery.vide.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/cardApp/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles%}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>校园卡支付管理系统</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body data-vide-bg="{% static 'img/chxy.MP4' %}">
<form class="form-login" action="/register/" method="post">
      {% if message %}
       <div class="alert alert-warning">{{ message }}</div>
       {% endif %}
       {% csrf_token %}

  <div class="login-form">
    <h2>欢迎注册</h2>
      {% csrf_token %}
    <div class="form-input">
        {{ register_form.username.label_tag }}
        {{ register_form.username}}
{#        <label>用户名：</label>#}
{#        <input type="text" id="id_username" class="form-control" name="username" autofocus required placeholder="用户名">#}
    </div>
    <div class="form-input">
        {{ register_form.password1.label_tag }}
        {{ register_form.password1 }}
{#        <label>密码：</label>#}
{#      <input type="password" class="form-control" id="id_password" placeholder="密码" name="password" required>#}
    </div>
      <div class="form-input">
          {{ register_form.password2.label_tag }}
          {{ register_form.password2 }}
{#        <label>确认密码：</label>#}
{#      <input type="password" class="form-control" id="id_password" placeholder="密码" name="password" required>#}
    </div>
      <div class="form-input">
          {{ register_form.email.label_tag }}
          {{ register_form.email }}
{#          <label>邮箱：</label>#}
{#      <input type="email" class="form-control" id="id_email" placeholder="姓名" name="email" required>#}
    </div>
      <div class="form-input">
          {{ register_form.name.label_tag }}
          {{ register_form.name }}
{#          <label>姓名：</label>#}
{#      <input type="text" class="form-control" id="id_name" placeholder="姓名" name="name" required>#}
    </div>
     <div class="form-input">
          {{  register_form.sex.label_tag}}
          {{  register_form.sex}}
{#          <label>校园卡号：</label>#}
{#      <input type="text" class="form-control" id="id_cardnum" placeholder="卡号" name="cardnum" required>#}
    </div>
      <div class="form-input">
          {{  register_form.card.label_tag}}
          {{  register_form.card}}
{#          <label>校园卡号：</label>#}
{#      <input type="text" class="form-control" id="id_cardnum" placeholder="卡号" name="cardnum" required>#}
    </div>
        <div class="form-input">
            {{ register_form.onlyid.label_tag }}
            {{ register_form.onlyid }}
{#          <label>身份证号码：</label>#}
{#      <input type="text" class="form-control" id="id_password" placeholder="身份证号码" name="onlyid" required>#}
    </div>
    <div class="form-input">
      <input type="submit" name='' value='提交'>
    </div>
    <a href="/login/" class="forget">直接登录</a>
  </div>
</form>
    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'js/jquery.vide.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>